# Generated by Django 4.0.4 on 2022-06-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0002_channel_user_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abuse_comments_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
